using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Wall : MonoBehaviour
{
    public GameObject block;
    public GameObject wallManager;
    public int width = 10; // wall width
    public int height = 4; // wall height

    // Start is called before the first frame update
    void Awake()
    {
        for (int y = 0; y < height; ++y)
        {
            for (int x = 0; x < width; ++x)
            {
                Instantiate(block, new Vector3(x, y + 0.5f, 3), Quaternion.identity, wallManager.transform);
            }
        }
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
